### ISSUE TITLE
Проверить регистрацию пользователей

### ISSUE THREAD

**Issue by ddrozdik** [drupal-russia/drupal-camp-krasnodar#1]
Проверить регистрацию пользователей, убедится что регистрация работает, письмо с деталями приходит. Проверить письмо, возможно его нужно отредактировать.

**Comment by afi13** [comment]
Проверил, текущий текст письма:

> Спасибо за регистрацию на сайте «DrupalCamp
> Краснодар 2016».
> 
> Ваши реквизиты:
> * адрес электронной почты: mail@example.com
> * пароль: password

Приходит от petr.beneficium@gmail.com
Может мыло поменяем?

**Comment by shagren** [comment]
Упс, и я проверил

**Comment by ddrozdik** [comment]
@pselfin есть ли емейл общий, типа camp@drupalyug.com

**Comment by ddrozdik** [comment]
Нужно изменить емейл на info@drupalyug.com

**Comment by shagren** [comment]
системное мыло измененно
