### ISSUE TITLE
Ссылки соц сетей

### ISSUE THREAD

**Issue by ddrozdik** [drupal-russia/drupal-camp-krasnodar#12]
Изменить ссылки соц сетей на ссылки краснодарской конференции. 

P.S. Сначала их должны создать.

**Comment by pselfin** [comment]
https://new.vk.com/drupalyug - Южное сообщество Drupal
https://new.vk.com/dckrd2016 - мероприятие DrupalCamp Краснодар 2016
https://twitter.com/drupalyug - оф твиттер южного сообщества
https://www.facebook.com/groups/drupal.russia/ - группа Drupal Russia (у локального сообщества нет своей группы в ФБ)
https://www.facebook.com/events/296297520708870/ - мероприятие DrupalCamp Краснодар 2016
инстаграмма - нет, и нахрен он нужен?)
https://www.youtube.com/user/drupalyug - Ютуб канал

**Comment by pselfin** [comment]
http://drupalyug.ru/ - оф сайт южного сообщества

**Comment by afi13** [comment]
Поменял ссылки в футере, Google Plus убрал
