### ISSUE TITLE
Настроить Twitter блок

### ISSUE THREAD

**Issue by ddrozdik** [drupal-russia/drupal-camp-krasnodar#14]

**Comment by ddrozdik** [comment]
https://twitter.com/drupalyug

**Comment by ddrozdik** [comment]
@pselfin Добавь сюда consumer key + consumer secret  для интеграции блока с твиттами на сайт

**Comment by pselfin** [comment]
Виджет с лентой
`<a class="twitter-timeline" href="https://twitter.com/drupalyug">Tweets by drupalyug</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>`

Consumer Key (API Key)	cF4XyGP2Cls54FAX7Rb7PcUt6
Consumer Secret (API Secret)	8bwd4eViSQDJJVDHwjpu86WxNTlO5CDFqJYbBIQSblfzn1dbG3

**Comment by afi13** [comment]
Готово
