### ISSUE TITLE
Дизайн бейджей для спонсоров

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/drupal-camp-krasnodar#17]
Тарифная сетка https://docs.google.com/spreadsheets/d/1rg4WFpwzU2v0gYfdHV3wPlEtLQ4fH679bJh789HYQr8/edit#gid=292381609

То есть, есть 

- 4 вида спонсоров, 
- 3 вида индивидуальных спонсоров, 
- информационные парнетры.

Пока больше не придумали
Пример Сибирского кемпа http://camp.drupalsib.ru/conference/materials

**Comment by ddrozdik** [comment]
Бейджи для спонсоров добавлены. Осталось 2 дополнительных чтоб занять место.

**Comment by pselfin** [comment]
@ddrozdik а как думаешь, исходники тоже на гитхаб выложить правильно будет, или там на сайте опубликовать? Или телиться "по запросу"?

**Comment by pselfin** [comment]
исходники дизайнерские имею ввиду

**Comment by ddrozdik** [comment]
@pselfin тут честно говоря на свое усмотрение. Зависит от того для каких целей исходники нужны.
