### ISSUE TITLE
Проверить добавление докладов

### ISSUE THREAD

**Issue by ddrozdik** [drupal-russia/drupal-camp-krasnodar#2]
Проверить добавление докладов, убедится что все работает.

**Comment by shagren** [comment]
Принципиально доклад добавляется
Необходимо пофиксить форматы текста/визивиг. Сейчас предлагает: Markdown, Plain text, Filtered html. Думаю выбор нужно убрать и всегда показывать визивиг.

Не переведены термины Тематика, Уровень аудитории.

**Comment by ddrozdik** [comment]
Согласен. Давай прятать и переведем термины.

**Comment by shagren** [comment]
Готово, необходимо поработать над дизайном формы
