### ISSUE TITLE
Минимальная высоты страницы

### ISSUE THREAD

**Issue by ddrozdik** [drupal-russia/drupal-camp-krasnodar#21]
Установить минимальную высоту страницы для страниц типа этой http://2016.drupalyug.ru/o-konferencii/contacts , чтоб футер не подпрыгивал

**Comment by ddrozdik** [comment]
@afi13 нужен небольшой js который пудет ставить min-height в случае если контент мало, чтоб футер не прыгал

**Comment by pselfin** [comment]
Вроде это все сделано. Закрываю
