### ISSUE TITLE
Настроить Mandrill

### ISSUE THREAD

**Issue by ddrozdik** [drupal-russia/drupal-camp-krasnodar#23]
Failed to load Mandrill API Key. Please check your Mandrill settings.
Невозможно отправить e-mail. Свяжитесь с администратором сайта, если проблема повторяется.

**Comment by pselfin** [comment]
а нам этот мандрил сильно нужен? Стандартная друпальная отправка не сгодится?

**Comment by afi13** [comment]
Отключил Mandrill, теперь письма приходят при регистрации
