### ISSUE TITLE
Стр. "Гостям Краснодара" (назначить на Никиту)

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/drupal-camp-krasnodar#25]
КОнтент для статьи http://2016.drupalyug.ru/conference/for-travelers
Вот часть достопримечательностей https://yadi.sk/d/DGAR-_Get2GuQ - можно "Новость" сделать и со страницы "Гостям" поставить ссылку.

**Comment by Normas95** [comment]
Написал контент простой, так как, Сергей Геннадьевич сказал, что пока быстро, потом можно доработать, все ссылки на сторонние сайты переделаны, просмотрите, и сообщите, если что исправить, доделать, позднее, добавлю картинки, и как локально разберусь, попробую добавить "Новость", вопрос по коду, в конце, как добраться текст сделан через div тэг, в остальных через p, играет ли это какую-то роль для вёрстки, или уже никто этим не будет заниматься?

**Comment by pselfin** [comment]
@Normas95 давай свой скайп, добавлю тебя в чатик, сможешь оперативно задавать вопросы и отвечать. 
Текст уже разместил?

**Comment by Normas95** [comment]
Да, текст уже разместил, можете зайти посмотреть, скайп: normas363

**Comment by Normas95** [comment]
И ещё вопрос, на английском тоже писать надо информацию?

**Comment by ddrozdik** [comment]
все готово, поправил ссылки на краснодар. англ вариант разместил.
