### ISSUE TITLE
Фотозона

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/drupal-camp-krasnodar#26]

**Comment by pselfin** [comment]
Есть надежда что наш небольшой музей казачества примет участие. Мне обещали поспособствовать в этом вопросе.

**Comment by mrsin** [comment]
Это будет потрясающе!

Надо друпликона мягкого сшить.

**Comment by pselfin** [comment]
Предварительное согласие Музей Казачества дал. На следующей неделе буду встречаться и обговаривать возможности.

**Comment by pselfin** [comment]
Согласие дали, с нас баннер скорее всего, пару тыщ потянет
