### ISSUE TITLE
Предоставить контакты знакомых видеооператоров

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/drupal-camp-krasnodar#27]
Сергей, ребятки которые вам снимали видео. Нужны контакты пообщаться.

**Comment by mrsin** [comment]
Они могут крутую заставку сделать для кемпа и монтаж. Можно промо ролик
кемпа заказать. Написал им предварительно, если смогут в эти даты, то
перешлю контакт ВК.

**Comment by pselfin** [comment]
Это классно! Такие нам нужны

**Comment by mrsin** [comment]
Закинул удочку, пусть думают что-то весёлое!

**Comment by pselfin** [comment]
Вот примерная задача им (знакомый мне еще чуть поможет с тз, но суть ясна думаю)

Задача видеооператорам
Что нужно снимать

Два официальных дня конференции
Два потока с докладами (Вероятно будет третий поток с “круглым столом”)
Церемония открытия/закрытия
Доклады (самое важное)
В идеале хотим получить на выходе видео докладов в таком виде - https://www.youtube.com/watch?v=JDgIXBEOaqM - то есть в одной части выступающий, в другой слайды доклада. 
Задача первая. Чтобы при монтировании было просто это все синхронизировать есть предложение делать скринкаст с монитора со слайдами (со звуком), а на видеокамеру крупным планом снимать докладчика. В таком варианте по звуку будет достаточно просто синхронизировать докладчика и слайды. 
Задача вторая. Звук. Звук с камеры без выносного микрофона в условиях аудитории, где работает кондиционер, шепчутся люди, кто-то ходит туда сюда… В общем, микрофоны для участников или какой-то иной способ решения проблемы.
Видео разумеется нужно в высоком разрешении - желательно Full HD
Другое
Желательно организовать репортажную съемку: как люди регистрируются, общаются на кофебрейке, церемонию открытия, закрытия. Планируем брать небольшие интервью.
Монтаж
Нужна будет заставка с логотипами спонсоров, организаторов, объявление докладчика и темы (можно в виде “плашечки”, как в новостных сайтах) сам доклад, и заключительная часть (титры?)

**Comment by mrsin** [comment]
Переслал

**Comment by pselfin** [comment]
Завтра на встречу с потенциальным оператором еду

**Comment by pselfin** [comment]
вся информация в гуглодоке, уже нужно делать предоплату.
