### ISSUE TITLE
Надо друпликона мягкого сшить

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/drupal-camp-krasnodar#29]
Идея сшить дркпальну голову, по типу сибиряков  - https://pp.vk.me/c627716/v627716862/3b268/JsHb2wxR288.jpg
Есть у меня пару умелиц знакомых...

**Comment by mrsin** [comment]
Боян, надо чет новое.

**Comment by pselfin** [comment]
Это пока как идея, чтобы не забыть.
Можно большую мягкую игрушку сшить.
костюм для аниматора - наверное лишнее, хотя....)

**Comment by pselfin** [comment]
сказали мне, голову за 3000р сшить могут

**Comment by pselfin** [comment]
@mrsin нужно нам это или нафиг? Или может дополнительные идеи есть?
