### ISSUE TITLE
Поправить стр. "Информация для спонсоров"

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/drupal-camp-krasnodar#31]
Адрес http://2016.drupalyug.ru/sponsors/info
Тарифная сетка: https://docs.google.com/spreadsheets/d/1rg4WFpwzU2v0gYfdHV3wPlEtLQ4fH679bJh789HYQr8/edit#gid=292381609

Перепроверить строки нашей таблицы и таблицы на сайте.
Добавить тарифы индивидуальных спонсоров

**Comment by ddrozdik** [comment]
@pselfin все корректно для русской версии. Индивидуальные тарифы описаны в текстовом виде под таблицей.

**Comment by pselfin** [comment]
В целом я поправил все.
Осталось только ссылки на Ком. Предложение актуализировать.

**Comment by ddrozdik** [comment]
Актуализировано.
