### ISSUE TITLE
Интегрировать робокассу

### ISSUE THREAD

**Issue by mrsin** [drupal-russia/drupal-camp-krasnodar#34]
Договор с Робокассой в процессе оформления на Катю. Сайт http://2016.drupalyug.ru/ я добавил.  Доступ на интеграцию передал Никите.

**Comment by mrsin** [comment]
Дмитрий, настрой пожалуйста интеграцию с робокассой, сайт в робокассу я добавил, выслал тебе доступ для настройки на стороне робокассы.

**Comment by mrsin** [comment]
Замечания от Робокассы по сайту:

1. В каталоге на Вашем сайте присутствуют алкогольные напитки. Подскажите, возможно ли исключить из ассортимента данную категорию товаров? (По условиям договора алкогольные напитки подразделяются как "Запрещенные услуги").

2. Разместите, пожалуйста, на сайте договор оферту/пользовательское соглашение с клиентом. Дополните и напишите нам.

**Comment by mrsin** [comment]
Дополнил оферту пунктом 1.3 про дополнительные услуги на сайте и вписал в раздел 2 про оплату через робокассу. Перезалейте пожалуйста PDF оферты.

**Comment by pselfin** [comment]
Размещен новый файл

**Comment by ddrozdik** [comment]
Интересно алкоголь они где нашли :)

**Comment by mrsin** [comment]
Уже разобрались, это они ошиблись.

**Comment by mrsin** [comment]
Робокасса активирована, можно принимать платежи. Нужно настроить товары -- платежи для индивидуальных спонсоров, вывести на страницах для спонсоров.
Оригиналы документов отправим позже, вывод средств будет доступен примерно с 15 августа.

**Comment by ddrozdik** [comment]
не актуально более, интегрировали яндекс деньги
