### ISSUE TITLE
Перевод главной страницы на English

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/drupal-camp-krasnodar#35]
Перевести текст главной страницы http://2016.drupalyug.ru/  на английский.
Он почти полностью скопирован у сибиряков, поэтому вот в помощь http://camp.drupalsib.ru/en
Авось только небольшие правки и понадобятся...

**Comment by RuZniki** [comment]
https://docs.google.com/document/d/1BTUQw91UPEB5mXSu6hOUusBvrlbCAsiqMUQtMLz87KU/edit?usp=sharing
