### ISSUE TITLE
Перевод на English

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/drupal-camp-krasnodar#36]
Перевести на английский страницы http://2016.drupalyug.ru/conference (многое можно смотреть на сайте http://camp.drupalsib.ru/en соотвественно)
- http://2016.drupalyug.ru/conference
- http://2016.drupalyug.ru/conference/for-travelers
- http://2016.drupalyug.ru/conference/for-speakers
- http://2016.drupalyug.ru/o-konferencii/contacts
- http://2016.drupalyug.ru/community
- http://2016.drupalyug.ru/community/code-of-conduct
- **Переведено** http://2016.drupalyug.ru/sponsors/info  - **важно**

**Comment by RuZniki** [comment]
https://docs.google.com/document/d/1BTUQw91UPEB5mXSu6hOUusBvrlbCAsiqMUQtMLz87KU/edit

**Comment by RuZniki** [comment]
Перевод готов. Можно размещать на сайт.
