### ISSUE TITLE
Адаптивная верстка

### ISSUE THREAD

**Issue by RuZniki** [drupal-russia/drupal-camp-krasnodar#37]
При ширине экрана 768-992 px адрес прочитать практически невозможно.
![Screenshot](http://i.imgur.com/oaK02QF.png)

**Comment by pselfin** [comment]
@ddrozdik Дим, если есть возможность посмотреть ситуацию с мобилками, будет очень круто.
Видео дает горизонтальную прокрутку.
На ифонах судя по отзыву одному какой-то пипец. С этим сафари всегра проблемы, а у меня даже нет его, чтоб проверить...

**Comment by ddrozdik** [comment]
Все готово. Проверьте у все ли норм теперь.
