### ISSUE TITLE
Разместить на сайт Английские статьи

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/drupal-camp-krasnodar#38]
Здесь главная и информация для спонсоров  https://docs.google.com/document/d/1BTUQw91UPEB5mXSu6hOUusBvrlbCAsiqMUQtMLz87KU/edit#heading=h.5w5chlwh2e78

**Comment by pselfin** [comment]
@Normas95  Никита, продолжай размещать, еще появились переводы https://docs.google.com/document/d/1BTUQw91UPEB5mXSu6hOUusBvrlbCAsiqMUQtMLz87KU/edit#heading=h.6subq8lu5om9

**Comment by ddrozdik** [comment]
Все тексты, помеченные зеленым уже размещены.
