### ISSUE TITLE
Анонс кемпа для информационных партнёров.

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/drupal-camp-krasnodar#39]
Необходимо написать анонс мероприятия, для размещения на сайтах информационных партнеров (блоги, СМИ, форумы и так далее).
Целевая аудитория: бизнесмены, программисты Друпалеры, программисты других технологий (включая другие языки программирования, фреймворки, CMS), студенты.
Формат участия: участники (все посетители мероприятия), докладчик и спонсоры. - нужно приглашать их всех.

Материалы.
Есть сайт конференции http://2016.drupalyug.ru
Есть вот такое видеоприглашение: http://2016.drupalyug.ru/conference/news/2016-07-25
Есть анонсы предыдущих кемпов:
- http://pro-self.ru/blog/pselfin/drupalcamp-msk-2014-28-29-noyabrya-moskva-mgu
- http://pro-self.ru/blog/pselfin/nakonec-pervyy-drupalcamp-v-sibiri
- http://www.cmsmagazine.ru/news/news_partners/1290/

Анонс должен мотивировать людей зарегистрироваться на сайте, приехать на кемп в формате участника/докладчика/спонсора.

В программе 2 дня с докладами, и 1 день полностью для неформального общения.

Лучше всего сделать анонс в гугл доке, чтобы мы его совместно доработали. 
По всем вопросам пиши - вк, скайп. Или сюда.

**Comment by RuZniki** [comment]
Создал файл в гугл доке 
https://docs.google.com/document/d/1OHSXNXIUsqTWGsD5euQauU-NrQA1SPAVo2r09fOBs3A/edit

Вот еще анонсы, которые мы готовили к D8 Release Party https://docs.google.com/document/d/1tGl9LgKeZ4Mefn7LpiCKnCzawQbmwsrv6SrNaj8Fgfw/edit

**Comment by RuZniki** [comment]
Черновик анонса готов, жду ваших предложений.
