### ISSUE TITLE
Настроить приходящие заявки о докладах 

### ISSUE THREAD

**Issue by ddrozdik** [drupal-russia/drupal-camp-krasnodar#4]
настроить приходящие заявки на почту пока что petr@selfin.pro, резерв petr.beneficium@gmail.com

**Comment by shagren** [comment]
Нет никаких заявок и извещений нет.
Глобальная почта настроена на petr.beneficium@gmail.com

**Comment by ddrozdik** [comment]
Нужно добавить отправку письма, с краткой информацией о поданном докладе.
