### ISSUE TITLE
Изображение для анонса

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/drupal-camp-krasnodar#40]
Дим, сделайте пожалуйста картинку для анонса кемпа на информационных сайтах.
пусть по ширине 1200 px будет - кому нужно уменьшит пропорции.
На картинке должен присутствовать 
- логотип
- дата
- город
- место
- адрес сайта

При том надписи достаточно крупные, чтобы при масштабе до 500px по ширине оставались читаемые.

**Comment by ddrozdik** [comment]
Вот 2 варианта 1920 и 1200
![baner 1200](https://cloud.githubusercontent.com/assets/6285570/17307049/cd5ff688-583b-11e6-8609-45ba3330bb0f.png)
![baner 1920](https://cloud.githubusercontent.com/assets/6285570/17307050/cd7fe48e-583b-11e6-8517-cd39e62e879f.png)

**Comment by pselfin** [comment]
@ddrozdik Дим, дай пожалуйста оригиналы баннеров, просят сайты отдельные элементы для встраивания. Спасибо!

**Comment by ddrozdik** [comment]
[baner .ai.zip](https://github.com/drupal-russia/drupal-camp-krasnodar/files/407172/baner.ai.zip)

@pselfin ^^
