### ISSUE TITLE
Пригласить инфоспонсоров

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/drupal-camp-krasnodar#41]
1. Собрать потенциальных инфопартнеров:
2. Собрать инфоспонсоров с сайтов предыдущих друпалкемпов
3. Собрать инфоспонсоров с других IT-конференций (погуглите. Темы SEO, Безопасность, Разработка, Программирование и тд)
4. Собрать интернет-СМИ и афиши краснодарские, федеральные, IT
5. Подготовить письмо с просьбой разместить анонс, либо зарегистрироваться на ресурсе и разместить анонс самостоятельно
6. У размещенных анонсов взять УРЛ анонса и логотип площадки (можно запросить) и добавить на сайт нашего кемпа

---

Сайты предыдущих кемпов:
- camp2014.drupalspb.org
- camp.drupalsib.ru
- 2014.drupalcampmsk.ru

Вот так неформально я приглашал друпалеров в соц.сетях. Можно это дело обофициалить

> Друзья! Помогите в распространении информации о грядущем DrupalCamp Краснодар 2016! 
> Разместите анонс мероприятия на видном месте у себя на сайте или в блоге и, пожалуйста, не снимайте его до окончания мероприятия. Так мы все вместе сможем максимально донести эту замечательную информацию всем нуждающимся!
> После этого пришлите на info@drupalyug.ru ссылку на анонс и ваш логотип - так вы попадете в раздел информационных партнёров.
> 
> Текст анонса здесь и материалы https://docs.google.com/document/d/1cBEnWc6Ck5fA3wD4ymWRuYUptN9QmmLny1BG17jFg4w/edit#heading=h.q7hqcf24sgcp

**Comment by Normas95** [comment]
Начал писать письма с просьбами о рекламе нашего мероприятия https://docs.google.com/a/initlab.ru/spreadsheets/d/1ljOaOMpzn6DvcXqpMDWsEYRU8WZJ9BCmUkRio5fdpGE/edit?usp=sharing чтобы все могли видеть для каких площадок и на какой стадии находится

**Comment by pselfin** [comment]
@mrsin  Сергей, закинь документ таблички в папку кемповскую, чтобы у актива был доступ

**Comment by mrsin** [comment]
@pselfin ссылку дай на папку? У меня нету. @Normas95 смени доступ у файла всем по ссылке, а не только в домене initlab.ru

**Comment by Normas95** [comment]
Сделано

**Comment by Normas95** [comment]
http://it-sobytie.ru/, Ребята ответили, сказали, что готовы размещать, это мне договариваться дальше, или Пётр уже дальше займётся?

**Comment by pselfin** [comment]
тебе
11 августа 2016 г., 20:59 пользователь Nikita <notifications@github.com>
написал:

> ята ответили, сказали, что готовы размещать, это мне договариваться
> дальше, или Пётр уже дальше займётся?
>



С уважением, *Пётр Селфин*
Специалист по интернет-маркетингу,
руководитель интернет-агентства "Selfin.Pro"

Персональный телефон:
*+7 928 42-98-094*Рабочий телефон: *+7 861 299-93-05*
Веб-сайт: http://selfin.pro
<http://selfin.pro?utm_source=email&utm_medium=petr-selfin-pro-gmail&utm_campaign=podpis>
Email: *petr@selfin.pro <petr@selfin.pro>*

**Comment by pselfin** [comment]
> ссылку дай на папку? 
@mrsin папка у тебя в гугл диске, в разделе "доступные", называется "Направления по кемпу"

**Comment by mrsin** [comment]
@pselfin не вижу папку, доступен только документ Анонс DrupalCamp Краснодар 2016.

**Comment by Normas95** [comment]
Посмотрите, пожалуйста, данный файл, я не знаю, стоит ли за такие цены размещаться н аданном сайте.
https://drive.google.com/file/d/0B4H9cghhCtAdZkJzVmVVZWVkZlU/view?usp=sharing

**Comment by pselfin** [comment]
@Normas95 нет, Никит. Нас интересует только бесплатное размещение)) Бюджета на это нет вообще(

**Comment by Normas95** [comment]
Принял, понял, буду общаться дальше тогда.

**Comment by pselfin** [comment]
@Normas95 Никит, давай за сегодня 50 штук пригласи. Можешь в гуглдок (мне право на редактирование petr.beneficium@gmail.com ) скинуть текст своего письма, авось подредактируем.
Давай даже так - не менее 50 писем в день. Ибо оооочень медленно все происходит.

**Comment by pselfin** [comment]
Где еще собирать потенциальных инфопартнеров? На сайтах вебмастерских конференций!
Например http://kinza.pro/ и http://balticdigitaldays.ru/

**Comment by Normas95** [comment]
Понял, это сделаем, доступ на письмо открыл, но я его иногда перед отправкой редактирую, там 2 варианта, один для разработчиков - друпалеров, второй для СМИ.

**Comment by pselfin** [comment]
@Normas95 оставил пару комментариев. Для СМИ надо более официально вступать, они понятия не имеют с кем общаются и что такое этот друпалкемп.

**Comment by Normas95** [comment]
Да, я уже увидел. Тогда для СМИ я полностью перепишу.

**Comment by mrsin** [comment]
Ребята, большие оффлайновые сми позовем рассылкой пресс-релиза от
университета, так больше вероятности что заинтересуются. Работайте по
профильным сайтам, сообществам, блогерам и т.д.

**Comment by pselfin** [comment]
@mrsin ты говоришь про участие на мероприятии (кстати, это тоже **уже пора сделать**), а Никита занимается размещением анонсов. Это дополниетльная тема.
Кстати, @Normas95 можно еще соцгруппы политеха, сельхоза и других найти, или прям ИТ-факультетов.

**Comment by Normas95** [comment]
Изменил текст письма для несведущих.

**Comment by Normas95** [comment]
Также изменил текст для разработчиков.

**Comment by Normas95** [comment]
Разослал ещё сообщений, завтра буду разбираться с недостоверностью хоста из-за которой нас считают спамом.

**Comment by pselfin** [comment]
@Normas95 Никит, кто разместил, добавляй их на сайт в инфоспонсоры.

**Comment by Normas95** [comment]
Понял, они просто не все присылают лого, кто присылает, я размещаю

**Comment by pselfin** [comment]
@Normas95 Никит, еще тема.
Во вконтакте ищешь друпал сообщества  ( https://vk.com/search?c%5Bq%5D=drupal&c%5Bsection%5D=communities ), пишешь админу, мол здравствуйте, я пишу вам как админу группы такой-то. У нас будет проходить друпалкемп, не могли бы вы сделать репост этой записи https://vk.com/wall-123654321_29. Мы думаем вашей аудитории этот анонс будет интересен.

И потом тоже самое можно по студентческим группам сделать, по краснодарским( просто региональные, и по бизнес-группам местным).

**Comment by pselfin** [comment]
и проси как разместят ссылку, мол, если не сложно как сделаете репост пришлите пожалйста ссылочку. 
Вежливость - наше главное оружие!)

**Comment by Normas95** [comment]
Ага, то есть, у нас вк есть новость уже, отлично!

**Comment by Normas95** [comment]
Некоторые сразу же откликнулись!
Завтра размещу по студенческим группам.
