### ISSUE TITLE
Квартиры посуточно

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/drupal-camp-krasnodar#42]
Найти квартиры посуточно, можно какого нибудь риелтора, кто занимается, чтобы предложить гостям города

**Comment by Normas95** [comment]
Я пока через друзей поспрашивал, обещали до пятницы мне выслать информацию, у кого, кто знакомые есть, но пока молчат.

**Comment by Normas95** [comment]
Вот документ, Сергей примерно объяснил, что спрашивать, там всех я обзвонил, Екатерину (последняя на данный момент) обязательно внимание обратить, там квартир 7-8 возле универа  1500/1800 в день на 4-6 человек, но двуспальные кровати, вот, завтра ещё пополню, но пока так

**Comment by pselfin** [comment]
https://docs.google.com/spreadsheets/d/14LesPV-54lX5h--VBofofvKg42jdqHQUISUM-H5Bevs/edit#gid=0

https://docs.google.com/document/d/1T1KbR9EykuGl9Z5CBxkFj9TOpDMd9HaTP6PStuxeynk/edit
