### ISSUE TITLE
Исходники дизайна - логотипы в вариациях и прочее

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/drupal-camp-krasnodar#43]
Дим, давай исходники.
В первую очередь нужен логотип, брелки заказывать будем

**Comment by ddrozdik** [comment]
[logo.zip](https://github.com/drupal-russia/drupal-camp-krasnodar/files/418038/logo.zip)

Вот, проверь, скажите подходит ли.

**Comment by pselfin** [comment]
@ddrozdik  а можно шрифт приложить, и экспортировать в SVG?
Ну или шрифт в кривые перевести.

**Comment by pselfin** [comment]
и монохром и цвет в svg с надписями в кривых.

**Comment by ddrozdik** [comment]
[logo-svg.zip](https://github.com/drupal-russia/drupal-camp-krasnodar/files/419827/logo-svg.zip)

**Comment by pselfin** [comment]
@ddrozdik   монохромный так открывается((
![logo kazak monochron](https://cloud.githubusercontent.com/assets/20221773/17696962/8ec44aac-63ba-11e6-8437-e8a2f7432a0e.jpg)

**Comment by ddrozdik** [comment]
[logo-svg.zip](https://github.com/drupal-russia/drupal-camp-krasnodar/files/420109/logo-svg.zip)

Вот, теперь должно быть все норм.
